### ISSUE TITLE
Add ADGUARD_ALLOW_UNTRUSTED_CERT option

### ISSUE THREAD

**Issue by Krafting** [henrywhitaker3/adguard-exporter#48]
Hello !

Would it be possible to add an option like ADGUARD_ALLOW_UNTRUSTED_CERT to allow quering HTTPS adguard instance using self-signed certificated ?

If set to true this option would allow using self-signed certificate.

Currently, if we are using self-signed certificate we have this error:

`2025/01/13 18:02:06 ERROR - could not get status: Get "https://xxxx/control/status": tls: failed to verify certificate: x509: certificate signed by unknown authority`

**Comment by Krafting** [comment]
I've been able to add my own CA to the container using a bind volume, I'll put my docker-compose config here if someone needs it later:

```
    volumes:
      - type: bind
        source: /srv/docker/CustomCA.pem
        target: /etc/ssl/certs/ca-custom.crt
        read_only: true
```
