### ISSUE TITLE
Arm64 dockerfile

### ISSUE THREAD

**Issue by beyondwatts** [henrywhitaker3/adguard-exporter#9]
I am getting an exec format error running the docker image on a raspberry pi. Would it be possible to update the Dockerfile to build adguard-exporter?

When I try to build the image currently I am receiving this error:
```
  Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "/adguard-exporter": permission denied: unknown
```

docker-compose.yml
```
version: "2"
services:
  adguard-exporter:
    build:
       dockerfile: ./adguard-exporter/Dockerfile
#    image: ghcr.io/henrywhitaker3/adguard-exporter:latest
    restart: always
    environment:
      ADGUARD_SERVERS: http://192.168.1.2
      ADGUARD_USERNAMES: demo
      ADGUARD_PASSWORDS: mypassword
      INTERVAL: 15s
    ports:
      - 9618:9618
```
